language: c++

cache: apt

dist: xenial

sudo: required

os:
  - linux
  - osx

compiler:
  - gcc

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo apt-get update;

      # C++17
      sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test;
      sudo apt-get install -qq g++-6;
      sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90;

      # Deps
      sudo apt-get install -qq build-essential xorg-dev libglu1-mesa-dev libglew-dev libglm-dev;
      sudo apt-get install -qq cmake;
      sudo apt-get install -qq libsdl2-dev;
      sudo apt-get install -qq libfftw3-dev;
    fi

  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew update;
      brew install sdl2;
      brew install fftw;
    fi

install:
  - echo "Install ..."

script:
  - mkdir build && cd build && cmake .. && make
